eslint:
  enabled: true
  config:
    extensions:
      - .js
      - .ts
      - .vue
ratings:
  paths:
    - '**.js'
    - '**.ts'
    - '**.vue'

exclude_patterns:
  - '__tests__/'
  - '__mocks__/'
  - '**/*.stories.ts'
